// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkID int32

const (
	NetworkID_UNKNOWN_NETWORK NetworkID = 0
	NetworkID_WHISPERNET      NetworkID = 1
	NetworkID_OCGF            NetworkID = 2
	NetworkID_FREQUENZ_X      NetworkID = 3
	NetworkID_NEON_LOTUS      NetworkID = 4
)

// Enum value maps for NetworkID.
var (
	NetworkID_name = map[int32]string{
		0: "UNKNOWN_NETWORK",
		1: "WHISPERNET",
		2: "OCGF",
		3: "FREQUENZ_X",
		4: "NEON_LOTUS",
	}
	NetworkID_value = map[string]int32{
		"UNKNOWN_NETWORK": 0,
		"WHISPERNET":      1,
		"OCGF":            2,
		"FREQUENZ_X":      3,
		"NEON_LOTUS":      4,
	}
)

func (x NetworkID) Enum() *NetworkID {
	p := new(NetworkID)
	*p = x
	return p
}

func (x NetworkID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkID) Descriptor() protoreflect.EnumDescriptor {
	return file_api_feed_proto_enumTypes[0].Descriptor()
}

func (NetworkID) Type() protoreflect.EnumType {
	return &file_api_feed_proto_enumTypes[0]
}

func (x NetworkID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkID.Descriptor instead.
func (NetworkID) EnumDescriptor() ([]byte, []int) {
	return file_api_feed_proto_rawDescGZIP(), []int{0}
}

type QuestState int32

const (
	QuestState_UNKNOWN_STATE QuestState = 0
	QuestState_AVAILABLE     QuestState = 1
	QuestState_IN_PROGRESS   QuestState = 2
	QuestState_COMPLETED     QuestState = 3
	QuestState_FAILED        QuestState = 4
)

// Enum value maps for QuestState.
var (
	QuestState_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "AVAILABLE",
		2: "IN_PROGRESS",
		3: "COMPLETED",
		4: "FAILED",
	}
	QuestState_value = map[string]int32{
		"UNKNOWN_STATE": 0,
		"AVAILABLE":     1,
		"IN_PROGRESS":   2,
		"COMPLETED":     3,
		"FAILED":        4,
	}
)

func (x QuestState) Enum() *QuestState {
	p := new(QuestState)
	*p = x
	return p
}

func (x QuestState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_feed_proto_enumTypes[1].Descriptor()
}

func (QuestState) Type() protoreflect.EnumType {
	return &file_api_feed_proto_enumTypes[1]
}

func (x QuestState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestState.Descriptor instead.
func (QuestState) EnumDescriptor() ([]byte, []int) {
	return file_api_feed_proto_rawDescGZIP(), []int{1}
}

type QuestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       string                 `protobuf:"bytes,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Network       NetworkID              `protobuf:"varint,4,opt,name=network,proto3,enum=feed.NetworkID" json:"network,omitempty"`
	State         QuestState             `protobuf:"varint,5,opt,name=state,proto3,enum=feed.QuestState" json:"state,omitempty"`
	Reward        int32                  `protobuf:"varint,6,opt,name=reward,proto3" json:"reward,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestEvent) Reset() {
	*x = QuestEvent{}
	mi := &file_api_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestEvent) ProtoMessage() {}

func (x *QuestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestEvent.ProtoReflect.Descriptor instead.
func (*QuestEvent) Descriptor() ([]byte, []int) {
	return file_api_feed_proto_rawDescGZIP(), []int{0}
}

func (x *QuestEvent) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *QuestEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuestEvent) GetNetwork() NetworkID {
	if x != nil {
		return x.Network
	}
	return NetworkID_UNKNOWN_NETWORK
}

func (x *QuestEvent) GetState() QuestState {
	if x != nil {
		return x.State
	}
	return QuestState_UNKNOWN_STATE
}

func (x *QuestEvent) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *QuestEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type FeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	mi := &file_api_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_api_feed_proto_rawDescGZIP(), []int{1}
}

func (x *FeedRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_api_feed_proto protoreflect.FileDescriptor

const file_api_feed_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/feed.proto\x12\x04feed\"\xe8\x01\n" +
	"\n" +
	"QuestEvent\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\tR\aquestId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\anetwork\x18\x04 \x01(\x0e2\x0f.feed.NetworkIDR\anetwork\x12&\n" +
	"\x05state\x18\x05 \x01(\x0e2\x10.feed.QuestStateR\x05state\x12\x16\n" +
	"\x06reward\x18\x06 \x01(\x05R\x06reward\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"*\n" +
	"\vFeedRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId*Z\n" +
	"\tNetworkID\x12\x13\n" +
	"\x0fUNKNOWN_NETWORK\x10\x00\x12\x0e\n" +
	"\n" +
	"WHISPERNET\x10\x01\x12\b\n" +
	"\x04OCGF\x10\x02\x12\x0e\n" +
	"\n" +
	"FREQUENZ_X\x10\x03\x12\x0e\n" +
	"\n" +
	"NEON_LOTUS\x10\x04*Z\n" +
	"\n" +
	"QuestState\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042D\n" +
	"\vFeedService\x125\n" +
	"\fStreamQuests\x12\x11.feed.FeedRequest\x1a\x10.feed.QuestEvent0\x01B\x1fZ\x1dzero_sum_rpg_backend/api/feedb\x06proto3"

var (
	file_api_feed_proto_rawDescOnce sync.Once
	file_api_feed_proto_rawDescData []byte
)

func file_api_feed_proto_rawDescGZIP() []byte {
	file_api_feed_proto_rawDescOnce.Do(func() {
		file_api_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_feed_proto_rawDesc), len(file_api_feed_proto_rawDesc)))
	})
	return file_api_feed_proto_rawDescData
}

var file_api_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_feed_proto_goTypes = []any{
	(NetworkID)(0),      // 0: feed.NetworkID
	(QuestState)(0),     // 1: feed.QuestState
	(*QuestEvent)(nil),  // 2: feed.QuestEvent
	(*FeedRequest)(nil), // 3: feed.FeedRequest
}
var file_api_feed_proto_depIdxs = []int32{
	0, // 0: feed.QuestEvent.network:type_name -> feed.NetworkID
	1, // 1: feed.QuestEvent.state:type_name -> feed.QuestState
	3, // 2: feed.FeedService.StreamQuests:input_type -> feed.FeedRequest
	2, // 3: feed.FeedService.StreamQuests:output_type -> feed.QuestEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_feed_proto_init() }
func file_api_feed_proto_init() {
	if File_api_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_feed_proto_rawDesc), len(file_api_feed_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_feed_proto_goTypes,
		DependencyIndexes: file_api_feed_proto_depIdxs,
		EnumInfos:         file_api_feed_proto_enumTypes,
		MessageInfos:      file_api_feed_proto_msgTypes,
	}.Build()
	File_api_feed_proto = out.File
	file_api_feed_proto_goTypes = nil
	file_api_feed_proto_depIdxs = nil
}
